(ci): Address timeouts, rate limiting; add tests
Squashed commit of the following:

commit f710f7f41a9f68450a9e05bc2df56866fe99fd0f
Author: Rafael Espinoza <rafael@rafaelespinoza.com>
Date:   Wed Jul 22 20:20:09 2026 -0700

    Add test coverage for delegator command, move tests

    Simplify the github actions workflow. It was written when the delegator
    was a shell script that routed commands to other binaries, in particular
    spots in the filesystem. So it seemed to make make sense then to try it
    out on different platforms, in various configurations.
    But now it's a golang command and is more self-contained than before, so
    the tests are simpler. Add some test coverage, I noticed a drop.

commit 7162a257bd989a7fc48152d36c543a7289c375e7
Author: Rafael Espinoza <rafael@rafaelespinoza.com>
Date:   Wed Jul 22 19:04:09 2026 -0700

    (cassandra): Add some unit tests

commit 44a18ba361958cc490c8716e33ac84f6ff1e5b0f
Author: Rafael Espinoza <rafael@rafaelespinoza.com>
Date:   Wed Jul 22 18:34:23 2026 -0700

    (ci): Increase timeouts for cassandra tests

    Every now and then the Cassandra DB does not respond in time. It's been
    a lot more noticeable lately, and it's starting to get annoying.

    Here are some sample errors:

      apply_migration.go:60: error dropping table in teardown: context deadline exceeded
      apply_migration.go:262: Migrate failed during setup: executing migration; path_to_file: forward-23450102030405-1.sql; Table 'godfish_test.foos' doesn't exist
      upgrade_schema_migrations.go:55: error executing query ("TRUNCATE TABLE schema_migrations") in teardown: context deadline exceeded

    Based on timestamps of nearby logs, I noticed that that the starts and
    ends of some tests, but not all, were roughly 2 seconds apart.

commit 490a508394c7d4323f6a94c143062a14ddd6748e
Author: Rafael Espinoza <rafael@rafaelespinoza.com>
Date:   Mon Jul 20 21:46:01 2026 -0700

    (ci): Pass GITHUB_TOKEN to integration test containers

    Have been getting a lot of these errors for integration tests that run
    the "upgrade" command, which involves using the GitHub API to install
    a previous version of this tool. When a bunch of tests begin running
    there's a good chance that at least one will end up like this:

        test_upgrade.sh
        client-1  |    install previous version 1/14 ✗ install previous version
        client-1  |    (in test file .ci/test_upgrade.sh, line 72)
        client-1  |      `assert_file_executable "${prev_bin}"' failed
        client-1  |
        client-1  |    -- file is not executable --
        client-1  |    path : /tmp/godfish_ipFLAf/bin/godfish_postgres
        client-1  |    --
        client-1  |
        client-1  |    Last output:
        client-1  |    wget: server returned error: HTTP/1.1 403 rate limit exceeded
        client-1  |    ERROR error downloading from https://api.github.com/repos/rafaelespinoza/godfish/releases/tags/v0.14.0
        client-1  |    bats warning: Executed 1 instead of expected 14 tests